version: 0.0
os: linux
files:
  - source: mysite.jar
    destination: /home/ubuntu/myapp/
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/mkdir.sh
      timeout: 30
      runas: root
  
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/install.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root

