apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot-container
          image: 731219765076.dkr.ecr.ap-northeast-2.amazonaws.com/my-springboot-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_DRIVER

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD

            - name: UPLOAD_PATH
              value: /mnt/efs/uploads
      volumes:
        - name: efs-volume
          persistentVolumeClaim:
            claimName: efs-pvc
